import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full antialiased">
      <body>
        <header>
          <NavBar />
        </header>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
